ALTER TABLE companies ADD COLUMN IF NOT EXISTS created_by_user_id UUID;
ALTER TABLE companies ADD CONSTRAINT fk_companies_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (user_id);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE companies ADD CONSTRAINT uq_companies_email UNIQUE (email);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS max_active_tests INTEGER NOT NULL DEFAULT 1;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS subscription_active BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS subscription_expiry_date TIMESTAMP;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS subscription_start_date TIMESTAMP;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE test_invite ADD COLUMN IF NOT EXISTS invitation_sent_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE test_invite ADD COLUMN IF NOT EXISTS updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
